### ISSUE TITLE
Unexpected error when trying to create panel

### ISSUE THREAD

**Issue by petersohn** [alexandrainst/alexandra-trackmap-panel#25] opened 2020-10-10 07:33 UTC
I installed the plugin to Grafana 7.2.1. When I tried creating a panel in Firefox 81.0.1, I  get the following error message:

```
TypeError: this.events is undefined
```

There are two error messages on the browser console:

```
Plugin component error Error: [$injector:unpr] Unknown provider: variableSrvProvider <- variableSrv
http://errors.angularjs.org/1.6.9/$injector/unpr?p0=variableSrvProvider%20%3C-%20variableSrv
    Angular 11
    f plugin_component.ts:223
    f plugin_component.ts:258
    link plugin_component.ts:266
plugin_component.ts:269:18
    link plugin_component.ts:269
```

```
TypeError: this.events is undefined
    value panel_ctrl.ts:66
    Angular 2
    React 13
    value Angular
react-dom.production.min.js:196:194
    React 17
    value Angular
```

It doesn't work on Chrome 86.0 either, but with a different error message:

```
plugin_component.ts:269 Plugin component error Error: [$injector:unpr] Unknown provider: variableSrvProvider <- variableSrv
http://errors.angularjs.org/1.6.9/$injector/unpr?p0=variableSrvProvider%20%3C-%20variableSrv
    at angular.js:116
    at angular.js:4887
    at Object.a [as get] (angular.js:5047)
    at angular.js:4892
    at a (angular.js:5047)
    at s (angular.js:5072)
    at Object.invoke (angular.js:5098)
    at angular.js:11076
    at it (angular.js:9926)
    at angular.js:9248****
```

```
react-dom.production.min.js:196 TypeError: Cannot read property 'emit' of undefined
    at MapCtrl.value (panel_ctrl.ts:66)
    at t.value (AngularPanelOptions.tsx:81)
    at t.value (AngularPanelOptions.tsx:49)
    at mc (react-dom.production.min.js:251)
    at KqkS.t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Wo (react-dom.production.min.js:120)
    at gc (react-dom.production.min.js:244)
    at ic (react-dom.production.min.js:223)
    at react-dom.production.min.js:121
    at KqkS.t.unstable_runWithPriority (scheduler.production.min.js:18)
```

**Comment by Alkarex** [comment] 2020-10-10 09:50
Duplicate of https://github.com/alexandrainst/alexandra-trackmap-panel/issues/18
Please try our release candidate https://github.com/alexandrainst/alexandra-trackmap-panel/pull/24
Tests feedback welcome

**Closed by Alkarex** 2020-10-10 09:50 UTC

**Comment by petersohn** [comment] 2020-10-10 14:29
I tried building the plugin from the branch, but `npm install` failed. Apparently it failed to install `path-type`. Here is the log file:

[npm-debug.log](https://github.com/alexandrainst/alexandra-trackmap-panel/files/5359180/npm-debug.log)

**Comment by j-or** [comment] 2020-10-13 09:13
Looks like an error with npm. Log file says "This is an error with npm itself." Maybe this https://github.com/npm/cli/issues/681
